# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('norecepieweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleExtensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Title')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='norecepieweb.TitleExtensions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
