# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norecepieweb', '0002_titleextensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleextensions',
            name='extended_object',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
    ]
